name: protomind-backend
recipe: laravel
config:
  webroot: public
  via: nginx
  php: '8.2'
services:
  appserver:
    type: php:8.2
    via: nginx
    webroot: public
    build_as_root:
      - chown -R www-data:www-data /app/storage/app/public
      - chmod -R 755 /app/storage/app/public
tooling:
  php:
    service: appserver
  composer:
    service: appserver
  artisan:
    service: appserver
